name       : darktable
version    : 2.4.2
release    : 33
source     :
    - https://github.com/darktable-org/darktable/releases/download/release-2.4.2/darktable-2.4.2.tar.xz : 19cccb60711ed0607ceaa844967b692a3b8666b12bf1d12f2242ec8942fa5a81
license    : GPL-3.0-only
summary    : darktable is an open source photography workflow application and RAW developer
component  : multimedia.graphics
description: |
    darktable is an open source photography workflow application and RAW developer. A virtual lighttable and darkroom for photographers. It manages your digital negatives in a database, lets you view them through a zoomable lighttable and enables you to develop raw images and enhance them.
builddeps  :
    - pkgconfig(colord-gtk)
    - pkgconfig(exiv2)
    - pkgconfig(glu)
    - pkgconfig(gnome-keyring-1)
    - pkgconfig(GraphicsMagick)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(lcms2)
    - pkgconfig(lensfun)
    - pkgconfig(libcurl)
    - pkgconfig(libexif)
    - pkgconfig(libgphoto2)
    - pkgconfig(libopenjp2)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libsecret-1)
    - pkgconfig(libssh)
    - pkgconfig(libturbojpeg)
    - pkgconfig(libtiff-4)
    - pkgconfig(libwebp)
    - pkgconfig(lua-5.3)
    - pkgconfig(OpenEXR)
    - pkgconfig(osmgpsmap-1.0)
    - pkgconfig(sdl)
    - pkgconfig(sqlite3)
    - cups-devel
    - openjdk-8
    - pugixml-devel
rundeps    :
    - gtk-engines
setup      : |
    mkdir build && cd build
    %cmake -DBINARY_PACKAGE_BUILD=ON -DLIB_SUFFIX=%LIBSUFFIX% ..
build      : |
    %make -C build
install    : |
    %make_install -C build
