name       : darktable
version    : 2.0.2
release    : 8
source     :
    - https://github.com/darktable-org/darktable/archive/release-2.0.2.tar.gz : 9ee6f7ce3be8cfe1108b356b9f5f9fc1d056ed51a2fefd7a79f46042b361bfa4
license    : GPL-3.0
summary    : darktable is an open source photography workflow application and RAW developer.
description: |
    darktable is an open source photography workflow application and RAW developer. A virtual lighttable and darkroom for photographers. It manages your digital negatives in a database, lets you view them through a zoomable lighttable and enables you to develop raw images and enhance them.
rundeps    :
    - gtk-engines
builddeps  : 
    - libjpeg-turbo-devel
    - pugixml-devel
    - openjdk-8
    - pkgconfig(colord)
    - pkgconfig(exiv2)
    - pkgconfig(gnome-keyring-1)
    - pkgconfig(GraphicsMagick)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(lcms2)
    - pkgconfig(glu)
    - pkgconfig(lensfun)
    - pkgconfig(libexif)
    - pkgconfig(libgphoto2)
    - pkgconfig(libopenjpeg1)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libsecret-1)
    - pkgconfig(libtiff-4)
    - pkgconfig(lua-5.1)
    - pkgconfig(libwebp)
    - pkgconfig(OpenEXR)
    - pkgconfig(sdl)
    - pkgconfig(sqlite3)
setup      : |
    mkdir build
    cd build
    %cmake -DBINARY_PACKAGE_BUILD=ON ..
build      : |
    cd build
    %make
install    : |
    cd build
    %make_install
