name       : darktable
version    : 3.0.1
release    : 48
source     :
    - https://github.com/darktable-org/darktable/releases/download/release-3.0.1/darktable-3.0.1.tar.xz : c54b3921da14a97c99ab2f79feca468cf2abca65adf907dba6216e47edab7cb7
license    : GPL-3.0-or-later
summary    : darktable is an open source photography workflow application and RAW developer
component  : multimedia.graphics
description: |
    darktable is an open source photography workflow application and RAW developer. A virtual lighttable and darkroom for photographers. It manages your digital negatives in a database, lets you view them through a zoomable lighttable and enables you to develop raw images and enhance them.
builddeps  :
    - pkgconfig(colord-gtk)
    - pkgconfig(exiv2)
    - pkgconfig(glu)
    - pkgconfig(gnome-keyring-1)
    - pkgconfig(GraphicsMagick)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(lcms2)
    - pkgconfig(lensfun)
    - pkgconfig(libcurl)
    - pkgconfig(libexif)
    - pkgconfig(libgphoto2)
    - pkgconfig(libopenjp2)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libsecret-1)
    - pkgconfig(libssh)
    - pkgconfig(libturbojpeg)
    - pkgconfig(libtiff-4)
    - pkgconfig(libwebp)
    - pkgconfig(lua-5.3)
    - pkgconfig(OpenEXR)
    - pkgconfig(osmgpsmap-1.0)
    - pkgconfig(sdl)
    - pkgconfig(sqlite3)
    - cups-devel
    - openjdk-8
    - pugixml-devel
rundeps    :
    - gtk-engines
setup      : |
    mkdir build && cd build
    %cmake -DBINARY_PACKAGE_BUILD=ON -DLIB_SUFFIX=%LIBSUFFIX% ..
build      : |
    %make -C build
install    : |
    %make_install -C build
